### PR TITLE
Blockchain network

### LINKED ISSUE #7: [BlockChain] get JSON transaction, block and chain

### PR DESCRIPTION
**Pull request by mxmaxime**
Methods on blockchain class:
- submit_block(block) -> block received from the network, I have to add it to my chain if the block is correct.
- ~~submit_transaction(transaction, signature) -> same thing as block but for transaction.~~
- submit_transaction(transaction) -> same thing as block but for transaction.

Property:
- chain_for_network -> returns my chain to be transmitted to the network.

TODO:
- When I'm creating a new transaction, I have to transmit it to the network. Something like network.send_transaction(transaction_as_str)
- Same for mined block.

Todo done by soso.

Fixes #7 #4

### CODE REVIEW

**Comment by mxmaxime** [comment]
"submit_transaction(transaction, signature) -> same thing as block but for transaction."
But on the network we don't have the signature. I have to handle this in my blockchain class.

**Comment by mxmaxime** [comment]
@soso0084 Create a method `network.ask_chain()` that will return an array of chains available on the network. You have to request all your nodes (that you're connected to), and return them as a JSON.

**Review by soso0084 — COMMENTED** [review]
broadcast_transaction(self, str_transaction_) for a transaction

**Review by soso0084 — COMMENTED** [review]
broadcast_block(self, str_block)

**Comment by mxmaxime** [comment]
I've changed the structure. The signature is now in the Transaction, so no more need to have it in parameters. submit_transaction(transaction, signature) -> submit_transaction(transaction).
Should be fine for you @soso0084

**Pull request merged**
